import Footer from "@Components/app/Footer";
import Header from "@Components/app/Header";
import CartWraper from "./CartWraper";

export const metadata = {
  title: "cart",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <>
      <CartWraper>
        {children}
      </CartWraper>
    </>
  );
}
